name: LuckyEssentials
version: 0.0.2
author: LyraMS
main: dev.luckynetwork.id.lyrams.LuckyEssentials

commands:
  gamemode:
    aliases: [gm, gmc, gms, gmsp, gma]
  feed:
    aliases: [eat]
  heal:
  fly:
  give:
    aliases: [i]
  teleport:
    aliases: [tp, tppos, tphere, s]