name: LuckyEssentials
version: 0.0.4
author: LyraMS
main: dev.luckynetwork.id.lyrams.LuckyEssentials
softdepend: [KtLoader]

commands:
  luckyessentials:
    aliases: [less, ess]
  gamemode:
    aliases: [gm, gmc, gms, gmsp, gma]
  feed:
    aliases: [eat]
  heal:
  fly:
  give:
    aliases: [i]
  teleport:
    aliases: [tp, tppos, tphere, s]
  clear:
    aliases: [ci]
  editsign:
  smite:
    aliases: [thor]
  explode:
  invsee:
  more:
  speed:
  kickall:
  fix:
  ewhitelist:
    aliases: [ewl]