name: LuckyEssentials
version: 1.0.6
author: LyraMS
main: dev.luckynetwork.id.lyrams.LuckyEssentials
softdepend: [MYSlots, LuckyInjector]

commands:
  luckyessentials:
    aliases: [less, ess]
  clear:
    aliases: [ci]
  ewhitelist:
    aliases: [ewl, wl, whitelist]
  feed:
    aliases: [eat]
  gamemode:
    aliases: [gm, gmc, gms, gmsp, gma]
  give:
    aliases: [i]
  smite:
    aliases: [thor]
  teleport:
    aliases: [tp, tppos, tphere, s]
  troll:
    aliases: [trolls]
  editsign:
  enchant:
  explode:
  fakeplace:
  fix:
  fly:
  getpos:
  god:
  heal:
  invsee:
  kickall:
  more:
  nobreak:
  nodamage:
  nohit:
  nointeract:
  nopickup:
  noplace:
  onetap:
  slots:
  speed:
  sudo:
  top: