name: LuckyEssentials
version: 0.0.5
author: LyraMS
main: dev.luckynetwork.id.lyrams.LuckyEssentials
softdepend: [MYSlots, LuckyInjector]

commands:
  luckyessentials:
    aliases: [less, ess]
  gamemode:
    aliases: [gm, gmc, gms, gmsp, gma]
  feed:
    aliases: [eat]
  give:
    aliases: [i]
  teleport:
    aliases: [tp, tppos, tphere, s]
  clear:
    aliases: [ci]
  smite:
    aliases: [thor]
  ewhitelist:
    aliases: [ewl]
  heal:
  fly:
  editsign:
  explode:
  invsee:
  more:
  speed:
  kickall:
  fix:
  slots:
  god:
  getpos:
  top:
  sudo:
  enchant: